version: '3'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=hawkergo

  ml-service:
    build: ./ml_model
    ports:
      - "5000:5000"
    env_file:
      - ./ml_model/.env
    volumes:
      - ./ml_model:/app
    restart: unless-stopped

  server:
      build: ./server
      ports:
        - "3000:3000"
      env_file:
        - ./server/.env
      volumes:
        - ./server:/app
      depends_on:
        - mongodb
        - ml-service
      restart: unless-stopped

  client:
    build: ./client
    ports:
      - "19000:19000"
      - "19001:19001"
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data: